services:
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  drinks-touch:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.drinks-touch_secure.tls.certresolver=default
    environment:
      ENV: PI
    image: flipdot/drinks-touch:0.3.43
    volumes:
    - (( replace ))
    - ./secrets/drinks-touch/config.py:/app/config.py:ro
    - /tmp/.X11-unix:/tmp/.X11-unix
  ldap: (( prune ))
  phpldapadmin: (( prune ))
  reset-touch:
  # Service script that resets the eGalax touchscreen offset.
    environment:
      DISPLAY: unix${DISPLAY}
    image: flipdot/reset-touch:0.0.1
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.httpChallenge.entryPoint=web
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
  traefik_certs-dumper:
  # See [DargStack template: certificates](https://github.com/dargmuesli/dargstack_template/#certificates).
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.4
    volumes:
    - acme_data:/etc/traefik/acme/
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}