services:
  adminer:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.middlewares=redirectscheme
      - traefik.http.routers.adminer.rule=Host(`adminer.${STACK_DOMAIN}`, `adminer.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.adminer_secure.rule=Host(`adminer.${STACK_DOMAIN}`, `adminer.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.adminer_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.adminer.loadbalancer.server.port=8080
    image: adminer:4@sha256:0ce7583815dabdd9f560ee0afed630ecb33df6756f4b66c85c197011559a0248
  drinks-touch:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.drinks-touch.middlewares=redirectscheme
      - traefik.http.routers.drinks-touch.rule=Host(`${STACK_DOMAIN}`, `${STACK_DOMAIN_LOCAL}`, `www.${STACK_DOMAIN}`, `www.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.drinks-touch_secure.rule=Host(`${STACK_DOMAIN}`, `${STACK_DOMAIN_LOCAL}`, `www.${STACK_DOMAIN}`, `www.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.drinks-touch_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.drinks-touch.loadbalancer.server.port=80
    environment:
      DISPLAY: ${DISPLAY}
    image: flipdot/drinks-touch:dev
    volumes:
    - ../../drinks-touch/drinks_touch/:/app/
  ldap:
    environment:
      LDAP_ADMIN_PASSWORD: admin
      LDAP_DOMAIN: flipdot.org
      LDAP_LOGIN_DN: dc=flipdot,dc=org
    image: osixia/openldap@sha256:3f68751292b43564a2586fc29fb7337573e2dad692b92d4e78e49ad5c22e567b
    ports:
    - 389:389
    - 639:639
  phpldapadmin:
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.routers.phpldapadmin.middlewares=redirectscheme
      - traefik.http.routers.phpldapadmin.rule=Host(`phpldapadmin.${STACK_DOMAIN}`, `phpldapadmin.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.phpldapadmin_secure.rule=Host(`phpldapadmin.${STACK_DOMAIN}`, `phpldapadmin.${STACK_DOMAIN_LOCAL}`)
      - traefik.http.routers.phpldapadmin_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.phpldapadmin.loadbalancer.server.port=80
    environment:
      PHPLDAPADMIN_HTTPS: "false"
    image: osixia/phpldapadmin:0.9.0@sha256:d112b82be1336f91e028b0348755133fda333992355b533419355a65c32ff9ad
    volumes:
    - phpldapadmin-data:/var/www/phpldapadmin
  postgres:
    environment:
      POSTGRES_DB: drinks
      POSTGRES_PASSWORD: postgres
    image: postgres:16.1-alpine@sha256:a6ff525294df1ba89cf0cb018ff772805dd93ada5d33ea6b11e47e6f46b97bee
    volumes:
    - postgres-data:/var/lib/postgresql/data
    - ../production/data/postgres/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    - ../production/data/postgres/02-drinks.sql:/docker-entrypoint-initdb.d/02-drinks.sql
  traefik:
    command:
    - --api=true
    - --entryPoints.web.address=:80
    - --entryPoints.web-secure.address=:443
    - --providers.docker=true
    - --providers.docker.endpoint=unix:///var/run/docker.sock
    - --providers.docker.exposedByDefault=false
    - --providers.docker.swarmMode=true
    - --providers.file.filename=/dynamic.yml #DARGSTACK-REMOVE
    - --providers.file.watch=true #DARGSTACK-REMOVE
    deploy:
      labels:
      - traefik.enable=true
      - traefik.http.middlewares.redirectscheme.redirectscheme.scheme=https
      - traefik.http.routers.traefik.middlewares=redirectscheme
      - traefik.http.routers.traefik.rule=Host(`traefik.${STACK_DOMAIN}`)
      - traefik.http.routers.traefik_secure.rule=Host(`traefik.${STACK_DOMAIN}`)
      - traefik.http.routers.traefik_secure.service=api@internal
      - traefik.http.routers.traefik_secure.tls.options=mintls13@file #DARGSTACK-REMOVE
      - traefik.http.services.traefik.loadbalancer.server.port=8080
      mode: global
      placement:
        constraints:
        - node.role == manager
    image: traefik:2.10.7@sha256:c5181ddf303f1ccfd4bd6d1d9c4867b0500efb6089a0f9ccb16612438f6e934f
    ports:
    - mode: host
      protocol: tcp
      published: 80
      target: 80
    - mode: host
      protocol: tcp
      published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./certificates/:/etc/traefik/acme/
    - ./configurations/traefik/dynamic.yml:/dynamic.yml:ro #DARGSTACK-REMOVE
version: "3.7"
volumes:
  phpldapadmin-data: {}
  postgres-data: {}
